app = "screwball"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
dockerfile = "Dockerfile"

[env]
DATA_PATH = "/data"
PORT = "8080"

[processes]
app = "/app/screwball"

[mounts]
source = "data"
destination = "/data"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[http_service.concurrency]
type = "connections"
soft_limit = 20
hard_limit = 25

[[http_service.checks]]
interval = "10s"
grace_period = "5s"
method = "GET"
path = "/healthcheck"
protocol = "http"
timeout = "2s"
